import React from 'react';
import { Link } from 'react-router-dom';
import './cayman.css';

class Home extends React.Component {
    render() {
        return (
            <div>
                <section className="page-header">
                    <h1 className="project-name">Kids Math</h1>

                    <h2 className="project-tagline">Kids math exercies.</h2>
                    <Link className="btn" to="/arithmetic">Addition in 20</Link>
                    <Link className="btn" to="/arithmetic">Substraction in 20</Link>
                    <Link className="btn" to="/arithmetic">Add/Sub in 20</Link>
                    <Link className="btn" to="/arithmetic">Arithmetic</Link>
                </section>
                <section className="main-content">
                    <h1>Introduction</h1>

                    <p>
                        This is a website dad and monther build for their kids. It include maths exercises from 5 years
                        to 10 years.
                    </p>

                    <p>
                        All the content are static hosted on <a href="https://github.com/kidsmath/kidsmath"
                                                                target="_blank">GitHub</a>.
                        You can use freely use all the content.
                        If you want to contribute this site feel free to fork send <a
                        href="https://github.com/kidsmath/kidsmath/pulls" target="_blank">pull request</a>.
                    </p>

                    <h1>License</h1>

                    <p>
                        This work is licensed under a <a href="http://creativecommons.org/licenses/by/4.0/"
                                                         target="_blank">Creative Commons Attribution 4.0
                        International</a> license.
                    </p>
                    <footer className="site-footer">
                        <span className="site-footer-credits">This page was generated by <a
                            href="https://pages.github.com" target="_blank">GitHub Pages</a> with <a
                            href="https://github.com/jasonlong/cayman-theme" target="_blank">Cayman</a> theme.
                        </span>
                    </footer>
                </section>
            </div>
        );
    }
}

export default Home;
